title: <p align="center"> Felipe Soto </p>

logo: "logofelipe.png?raw=true"

description:
  <p align="center">
  <a href="FelipeSoto_Resume_Data_Analyst_español.pdf">Currículum</a> |
  <a href="https://www.linkedin.com/in/fssantibanez/">LinkedIn</a> |
  <a href="https://github.com/fsaantibanez">GitHub</a>
  </p>
  
  <p align="justify">
  Data Analyst con +3 años de experiencia en CRM, Analytics y Marketing en Chile y Brasil 
  implementando soluciones para distintas empresas como Banco Falabella y Enseña Chile.
  <br><br>
  Actualmente me desempeño como Ayudante de docencia de la carrera de Data Science en la Academia Desafío Latam.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
